### PR TITLE
Removed filename and runtime

### PR DESCRIPTION
**Pull request by treeder**

### CODE REVIEW

**Comment by rdallman** [comment]
can't these still be returned by old workers? :(

**Comment by treeder** [comment]
Hmm, good question. I guess maybe turning them into pointers would suffice, they're getting passed around when they're not wanted.

**Comment by rdallman** [comment]
pointers seems like a good plan, could mark as deprecated next to them in comments

**Comment by treeder** [comment]
Mind you, these are super old now, pre image and stack. Think anyone using Go lib would have those?

**Comment by rdallman** [comment]
could always break it and if people scream put it back (seems ok to see). looks like it removes stack which afaik is what most customers use, could we leave stack ?

**Comment by treeder** [comment]
I'll just pointer and/or omitempty all these things.

**Pull request closed without merging**
